api_secret_key = "api_secret_key" #vi har url i koden men man kan hänvisa till denna också

[destination.snowflake.credentials]
database = "econom_ads" 
password = "password" 
username = "username" 
host = "<youridhere>.west-europe-azure" 
warehouse = "COMPUTE_WH" 
role = "econom_dlt_role"
