models:
  - name: dim_employer
    columns:
      - name: employer_id
        data_tests:
          - unique
          - not_null

      - name: workplace_city
        data_tests:
          - not_null
   
      - name: employer_name
        description: "Name of the employer"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_not_match_regex:
              regex: '^$'     
  
  - name: dim_job_details
    columns:
      - name: econom_details_id
        data_tests:
          - not_null
          - unique

      - name: headline
        data_tests:
          - not_null

      - name: employment_type
        data_tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Behovsanställning', 'Vanlig anställning', 'Arbete utomlands']
          - dbt_expectations.expect_column_values_to_not_match_regex:
              regex: '^$'

  - name: fct_job_ads
    columns:
      - name: job_details_key
        data_tests:
          - relationships:
              to: ref('dim_job_details')
              field:  econom_details_id
      - name: relevance
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 1 

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: vacancies
        data_tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 50
              config:
                severity: warn

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
    
